[package]
name = "opengl_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.24"
three-d = "0.17.0"
three-d-asset = "0.7.0"
